#!/usr/bin/env python3
"""Cross-reference checker for RONIN internal symbols.

The sandbox has no AndroidX jars, so kotlinc reports every AndroidX symbol as
unresolved. This script instead verifies that every *project-internal* symbol
referenced anywhere is actually declared somewhere in the project.
"""
import re, pathlib, sys, collections

root = pathlib.Path('app/src/main/java/com/ronin/ai')
files = sorted(root.rglob('*.kt'))
src = {f: f.read_text() for f in files}

decl = collections.defaultdict(set)
decl_re = re.compile(
    r'^\s*(?:@\w+\s+)*(?:public |internal |private |abstract |open |sealed |data |enum |value )*'
    r'(?:class|object|interface|fun|val|var)\s+(?:<[^>]*>\s+)?'
    r'(?:[A-Za-z_][\w.<>, ?]*\.)?([A-Za-z_]\w*)', re.M)
for f, t in src.items():
    for m in decl_re.finditer(t):
        decl[m.group(1)].add(f)
    # enum entries + property names in constructors
    for m in re.finditer(r'^\s{4}([A-Z][A-Z0-9_]*)\s*[(,;]', t, re.M):
        decl[m.group(1)].add(f)

declared = set(decl)
for gen in ('R', 'BuildConfig'):  # generated by AGP at build time
    declared.add(gen)

# Imports of com.ronin.* must resolve to a declaration
missing = []
for f, t in src.items():
    for m in re.finditer(r'^import (com\.ronin\.ai\.[\w.]+)', t, re.M):
        fq = m.group(1)
        sym = fq.split('.')[-1]
        if sym == '*':
            continue
        if sym not in declared and sym[0].isupper():
            missing.append((f, fq))
        elif sym not in declared and sym[0].islower():
            missing.append((f, fq))

print(f"kotlin files      : {len(files)}")
print(f"declared symbols  : {len(declared)}")
print(f"broken imports    : {len(missing)}")
for f, fq in missing:
    print(f"  {f.relative_to(root)} -> {fq}")
sys.exit(1 if missing else 0)
